enyo.depends(
	"$lib/layout",
	"$lib/extra/analyzer2/",
	"foss/showdown-v0.9/compressed/showdown.js",
	"foss/syntaxhighlighter_3.0.83_fork/sh-min.css",
	"foss/syntaxhighlighter_3.0.83_fork/sh-min.js",
	"extra",
	"presentors",
	"PackagesEditor.js",
	"PackageList.js",
	"TabPanels.js",
	"SearchBar.js",
	"App.css",
	"App.js",
	"presentation.css"
);